### ISSUE TITLE
Non-ASCII characters misdisplayed in music

### ISSUE THREAD

**Issue by jw35** [jw35/EasyABC#9]
> One bug I’ve noticed is that accented characters (acute a and e, grave a and e) don’t display correctly. I’d guess this may be related to an already-reported bug involving display of time signature and tune title.
Here is an example where the é in the tune title has been replaced with junk:

![Screen Shot 2019-11-06 at 9 03 42 AM](https://user-images.githubusercontent.com/2385623/68374710-4aee8580-013d-11ea-98f5-f8843356afcb.png)

**Comment by jw35** [comment]
Probably the result of moving from Python 2 to Python 3

**Comment by jw35** [comment]
And again:

>I was working on building up a collection of Russian folk songs, and came back to it today to find that EasyABC is not displaying Unicode characters, but rather is showing the two-byte representation. Don't understand why, it is the same version of the software. I did install the public beta of 10.15.4 Beta (19E224g) so it may be related to that... Just FYI, probably nothing to be done about it.

**Comment by jw35** [comment]
Seems to be fixed in the current version - probably as a result of a abcm2ps upgrade.

**Comment by n9yty** [comment]
I just downloaded a new version (as posted in ticke on sourceforge https://sourceforge.net/p/easyabc/tickets/36/#9edb ) but it has not fixed it for me here.  But maybe that is not using the latest version that had the fix in it?
